[package]
name = "const_replace"
version = "0.1.0"
edition = "2021"

[dependencies]
swc_core = { version = "0.97.5", features = ["common", "ecma_ast", "ecma_parser", "ecma_visit", "ecma_transforms", "ecma_codegen"] }
serde_json = "1"
serde = "1"